In [1]:
import numpy as np
import pandas as pd

***Pivot Tables***

In [2]:
# Create data
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South'] * 5,
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice'] * 5
}

# Create DataFrame
df = pd.DataFrame(data)

# Extra columns
df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    205     47   John  January      Q1
1  2023-01-02       B   West    780     23   Mary  January      Q1
2  2023-01-03       C  North    320     20    Bob  January      Q1
3  2023-01-04       D  South    879     79  Alice  January      Q1
4  2023-01-05       A   East    210     54   John  January      Q1
5  2023-01-06       B   West    705     29   Mary  January      Q1
6  2023-01-07       C  North    122     64    Bob  January      Q1
7  2023-01-08       D  South    192     80  Alice  January      Q1
8  2023-01-09       A   East    859     67   John  January      Q1
9  2023-01-10       B   West    836     45   Mary  January      Q1
10 2023-01-11       C  North    846     80    Bob  January      Q1
11 2023-01-12       D  South    598     88  Alice  January      Q1
12 2023-01-13       A   East    102     30   John  January      Q1
13 2023-01-14       B   West    154     38   Mary  January      Q1
14 2023-01-15       C  North    194     79    Bob  January      Q1
15 2023-01-16       D  South    366     68  Alice  January      Q1
16 2023-01-17       A   East    588     98   John  January      Q1
17 2023-01-18       B   West    508     75   Mary  January      Q1
18 2023-01-19       C  North    857     73    Bob  January      Q1
19 2023-01-20       D  South    331     65  Alice  January      Q1

In [6]:
pd.pivot_table(df,values = "Sales", index = 'Region', columns = "Product",aggfunc = "median")

Product      A      B      C      D
Region
East     210.0    NaN    NaN    NaN
North      NaN    NaN  320.0    NaN
South      NaN    NaN    NaN  366.0
West       NaN  705.0    NaN    NaN

In [7]:
pivot2 = pd.pivot_table(df,values=["Sales","Units"],index = 'Region', columns = "Product")
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     392.8    NaN    NaN    NaN  59.2   NaN   NaN   NaN
North      NaN    NaN  467.8    NaN   NaN   NaN  63.2   NaN
South      NaN    NaN    NaN  473.2   NaN   NaN   NaN  76.0
West       NaN  596.6    NaN    NaN   NaN  42.0   NaN   NaN

***Cross Tabs***

In [8]:
pd.crosstab(df["Region"],df["Product"])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0